library(tidyverse)
murders <- read.csv("data/murders.csv")
head(murders, 10)
murders <- murders %>% mutate(region2 = factor(region), rate = total / population * 10^5)
save(murders, file = "rda/murders.rda")
